language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'

before_script:
- npm install -g @angular/cli
# - npm install
script: npm run build

before_deploy:
  - npm run docs
  - npm run packagr
  - cd dist
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    local-dir: docs
    on:
      branch: master
after_deploy:
  - cd ..
