language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'

before_script:
- npm install -g @angular/cli
# - npm install
script: npm run build

before_deploy:
  - npm run packagr
  - cd dist
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master

before_deploy_pages:
  - npm run build
deploy_pages:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: dist
  on:
    branch: master
